apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: curl
  name: curl
spec:
  containers:
  - image: curlimages/curl
    name: curl
    command:
    - "sleep"
    - "1000"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: master-1
status: {}
