apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network
spec:
  podSelector:
   matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
           app: curl
    ports:
    - port: 80
      protocol: TCP


