apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network
spec:
  podSelector:
   matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
       cidr: 10.0.0.0/8
    - podSelector:
          matchLabels:
             app: curl
    ports:
    - port: 80
      protocol: TCP
    
    
