apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: network-policy
spec:
  containers:
  - image: nginx
    name: network-policy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
