#kubectl create configmap html-config --from-file=index.html
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: configmap-volume
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30111
  selector:
    app: nginx
    purpose: configmap-volume
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: configmap-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      purpose: configmap-volume
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
        purpose: configmap-volume
    spec:
      containers:
      - image: nginx
        name: configmap-volume
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: data-volume
          subPath: index.html
      volumes:
      - name: data-volume
        config:
          configName: html-config
