apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: read-pods
    namespace: default
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: pod-reader
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: user1
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: user2
kind: List
