apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syamsundar
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
  - delete
- apiGroups:
  - extensions
  resources:
  - deployments
  - daemonsets
  verbs:
  - list
  - get
  - watch
  - delete
