apiVersion: v1
kind: Service
metadata:
  name: simple-web-color-secrets
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30103
  selector:
    run: simple-web-color-secrets
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: simple-web-color
  name: simple-web-color-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      run: simple-web-color-secrets
  template:
    metadata:
      labels:
        run: simple-web-color-secrets
    spec:
      containers:
      - envFrom:
        - secretRef:
             name: app-config
        image: mmumshad/simple-webapp-color
        name: simple-web-color
        ports:
        - containerPort: 8080
