apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: initcontainer
  namespace: application-lifecycle
spec:
  containers:
  - image: nginx
    name: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    resources: {}
    imagePullPolicy: IfNotPresent
  initContainers:
  - image: nginx
    name: nginx1
    command: ["sleep","100"]
    imagePullPolicy: IfNotPresent
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
