---
apiVersion: v1
kind: Pod
metadata:
  labels:
    application: nginx
  name: multicontainer
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
  - image: nginx
    name: nginx1
    command: ["sleep", "1000"]
    imagePullPolicy: IfNotPresent
  dnsPolicy: ClusterFirst
  restartPolicy: Always
