apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: my-custom-scheduler
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    resources:
      limits:
        cpu: "100"
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
  schedulerName: my-custom-scheduler
