apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: manual-scheduling
spec:
  containers:
  - image: nginx
    name: manual-scheduling
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: worker-2
