apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: node-affinity
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: env
                      operator: In
                      values:
                      - test
  tolerations:
  - key: "test"
    operator: "Equal" 
    value: "syam"
    effect: "NoSchedule"
