apiVersion: v1
kind: Pod
metadata:
  name: resource-limits
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        cpu: "100"
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
