apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: taint-tolerations
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
  tolerations:
  - key: "test"
    operator: "Equal" 
    value: "syam"
    effect: "NoSchedule"
