---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: pvc
spec:
  containers:
  - image: redis
    name: pvc
    ports:
    - containerPort: 6379
    resources: {}
    volumeMounts:
    - name: pvc
      mountPath: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: pvc
    persistentVolumeClaim:
         claimName: task-pv-claim
  #- name: aws-volume
    # This AWS EBS volume must already exist.
    #awsElasticBlockStore:
    #volumeID: <volume-id>
       #fsType: ext4
  #- name: gcp-volume
    # This GCE PD must already exist.
    #gcePersistentDisk:
      #pdName: my-data-disk
      #fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
status:
  loadBalancer: {}

