---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: simple-web-color-secrets-volume
  name: simple-web-color-secrets-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      run: simple-web-color-secrets-volume
  template:
    metadata:
      labels:
        run: simple-web-color-secrets-volume
    spec:
      containers:
      - envFrom:
        - secretRef:
             name: app-config
        image: mmumshad/simple-webapp-color
        name: simple-web-color
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets-volume
          mountPath: /opt
      volumes:
      - name: secrets-volume
        secret:
           secretName: app-config
