---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: simple-web-color-configmap-volume
  name: simple-web-color-configmap-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      run: simple-web-color-configmap-volume
  template:
    metadata:
      labels:
        run: simple-web-color-configmap-volume
    spec:
      containers:
      - envFrom:
        - configMapRef:
             name: app-config
        image: mmumshad/simple-webapp-color
        name: simple-web-color
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /opt
      volumes:    
      - name: config-volume
        configMap:
           name: app-config
